### PR TITLE
Migrated to nnbd.

### PR DESCRIPTION
**Pull request by bsutton**
This PR converts flip to null safety.

Can you please accept this PR and publish an updated version to pub.dev.

Thanks.

### CODE REVIEW

**Comment by bsutton** [comment]
@js94766524 

Any chance you can accept this PR?

2.12 is now released!

**Comment by js94766524** [comment]
Thank you, but bad news, I have no vpn to publish a new version to pub.dev now.
Perhaps you can import this widget by github link or else.
Sorry!

**Comment by benitogonzalezh** [comment]
+1

**Comment by js94766524** [comment]
> @js94766524
> 
> Any chance you can accept this PR?
> 
> 2.12 is now released!

I have published this PR! Sorry for your waiting

**Pull request merged**
